### ISSUE TITLE
restrict qualify allocated array-pointer

### ISSUE THREAD

**Issue by kevyonan** [embedded2016/raytracing#6]
https://github.com/embedded2016/raytracing/blob/928b200d8b6d0d01f9c2ae76f6c8288032aba078/raytracing.c#L456

replace
```c
uint8_t *pixels, ...
```
with
```c
uint8_t pixels[restrict static 1], ...
```
`static` is because the compiler will know that `pixels` is never called when `NULL` so it'll optimize further.

**Comment by jserv** [comment]
Thank @assyrianic for reporting. Can you show me some measurements because of such room for compiler optimizations?

**Comment by kevyonan** [comment]
actually, I rescind my original comment but I did notice _something else_, you're using a linked list in place of a dynamic array, why is that?

**Comment by jserv** [comment]
> actually, I rescind my original comment but I did notice _something else_, you're using a linked list in place of a dynamic array, why is that?

The raytracing program was intended to be improved by my students who attended the system programming course. I expect the students can facilitate profiling tool to figure out the hidden area to be enhanced including the inefficient data structure.

**Comment by kevyonan** [comment]
I see! I would've loved to be in your class then. Also the restrict qualifier didn't have much effect but I did find that the static qualifier had a (insigificant) effect.

I would think perhaps the math could be sped up a bit by utilizing pointers to arrays for the vector math
